ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/wake_gesture
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/tilt_detector

obj-y := bma4.o bma423.o bma4xy_i2c.o bma4xy_driver.o
